services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cerply
      POSTGRES_PASSWORD: cerply
      POSTGRES_DB: cerply
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  ai:
    image: python:3.11
    working_dir: /srv
    volumes:
      - ./ai:/srv
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8090 --reload"
    ports:
      - "8090:8090"

  api:
    image: node:20
    working_dir: /app
    volumes:
      - ./api:/app
    environment:
      PORT: 8080
      AI_URL: http://ai:8090
      DATABASE_URL: postgres://cerply:cerply@db:5432/cerply
      FF_CURATOR_DASHBOARD_V1: "true"
      FF_ADAPTIVE_ENGINE_V1: "true"
      FF_TRUST_LABELS_V1: "true"
    depends_on:
      - ai
      - db
    command: sh -c "npm install && npm run dev"
    ports:
      - "8081:8080"

  web:
    image: node:20
    working_dir: /web
    volumes:
      - ./web:/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8081
      NEXT_PUBLIC_FF_CURATOR_DASHBOARD_V1: "true"
      NEXT_PUBLIC_FF_ADAPTIVE_ENGINE_V1: "true"
      NEXT_PUBLIC_FF_TRUST_LABELS_V1: "true"
    depends_on:
      - api
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

volumes:
  minio-data:
