
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cerply
      POSTGRES_PASSWORD: cerply
      POSTGRES_DB: cerply
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio-data:/data
  api:
    image: node:20
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "npm install && npm run dev"
    environment:
      PORT: 8080
      AI_URL: http://ai:8090
    depends_on: [ai]
    ports: ["8080:8080"]
  ai:
    image: python:3.11
    working_dir: /srv
    volumes:
      - ./ai:/srv
    command: bash -lc "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8090 --reload"
    ports: ["8090:8090"]
  web:
    image: node:20
    working_dir: /web
    volumes:
      - ./web:/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    command: sh -c "npm install && npm run dev"
    depends_on: [api]
    ports: ["3000:3000"]
volumes:
  minio-data:
