services:
  - type: web
    name: cerply-api
    env: node
    rootDir: api
    plan: starter
    region: frankfurt
    branch: staging
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: OPENAI_API_KEY
        sync: false            # supply via Render dashboard after first sync
      - key: DATABASE_URL
        value: "file:./.data/staging.sqlite"  # Use SQLite for staging environment
      - key: LLM_PREVIEW
        value: "1"
      - key: LLM_PLANNER_MODEL
        value: gpt-4o-mini
      - key: LLM_PLANNER_PROVIDER
        value: openai
      - key: CERTIFIED_ENABLED
        value: "true"
      - key: RETENTION_ENABLED
        value: "true"
