
openapi: 3.0.3
info: { title: Cerply Core API, version: "0.1.0" }
paths:
  /health:
    get: { summary: Liveness }
  /api/certified/plan:
    post:
      summary: Certified plan
      description: |
        Returns a stub (501) by default when `CERTIFIED_MODE=stub`.
        When `CERTIFIED_MODE=mock`, returns a deterministic mock plan (200).
      responses:
        '200':
          description: Mock plan (when CERTIFIED_MODE=mock)
          content:
            application/json:
              schema:
                type: object
                required: [status, request_id, endpoint, mode, enabled, provenance, plan]
                properties:
                  status: { type: string, enum: [ok] }
                  request_id: { type: string }
                  endpoint: { type: string, enum: [certified.plan] }
                  mode: { type: string, enum: [mock] }
                  enabled: { type: boolean }
                  provenance:
                    type: object
                    required: [planner, proposers, checker]
                    properties:
                      planner: { type: string }
                      proposers:
                        type: array
                        items: { type: string }
                      checker: { type: string }
                  plan:
                    type: object
                    required: [title, items]
                    properties:
                      title: { type: string }
                      items:
                        type: array
                        items:
                          type: object
                          required: [id, type, front, back]
                          properties:
                            id: { type: string }
                            type: { type: string, enum: [card] }
                            front: { type: string }
                            back: { type: string }
        '501':
          description: Stub (default when CERTIFIED_MODE=stub)
          content:
            application/json:
              schema:
                type: object
                required: [status, endpoint, request_id, enabled, message]
                properties:
                  status: { type: string, enum: [stub] }
                  endpoint: { type: string, enum: [certified.plan] }
                  request_id: { type: string }
                  enabled: { type: boolean }
                  message: { type: string }
  /ingest/policy:
    post:
      summary: Register a policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: { name: { type: string }, text: { type: string } }
      responses: { '201': { description: Created } }
  /rde/decompose:
    post:
      summary: Decompose policy text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: { policyId: { type: string }, text: { type: string } }
      responses: { '200': { description: OK } }
  /evidence/coverage:
    get:
      summary: Evidence coverage
      parameters: [ { in: query, name: scopeId, schema: { type: string } } ]
      responses: { '200': { description: OK } }
  /api/orchestrator/jobs:
    post:
      summary: Submit Task Packet (preview)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [goal, limits]
              properties:
                goal: { type: string }
                scope: { type: string }
                planRef: { type: string }
                steps:
                  type: array
                  items:
                    type: object
                    properties:
                      id: { type: string }
                      type: { type: string }
                      payload: { }
                limits:
                  type: object
                  required: [maxSteps, maxWallMs]
                  properties:
                    maxSteps: { type: integer }
                    maxWallMs: { type: integer }
                flags: { type: object }
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                required: [job_id]
                properties:
                  job_id: { type: string }
  /api/orchestrator/jobs/{id}:
    get:
      summary: Get job status (preview)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
        '404': { description: Not found }
  /api/orchestrator/jobs/{id}/logs:
    get:
      summary: Get recent logs (preview)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
        - in: query
          name: n
          required: false
          schema: { type: integer, minimum: 1, maximum: 200 }
      responses:
        '200': { description: OK }
        '404': { description: Not found }
  /api/orchestrator/jobs/{id}/cancel:
    post:
      summary: Cancel job (idempotent; preview)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
        '404': { description: Not found }
  /api/orchestrator/events:
    get:
      summary: Stream job events (SSE, preview)
      parameters:
        - in: query
          name: job
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /api/admin/certified/sources:
    get:
      summary: List admin sources (ADMIN_PREVIEW=true)
      security:
        - AdminToken: []
      parameters:
        - in: query
          name: q
          required: false
          schema: { type: string, maxLength: 200 }
          description: Search query for name/url
        - in: query
          name: page
          required: false
          schema: { type: integer, minimum: 1 }
          description: Page number for pagination
        - in: query
          name: limit
          required: false
          schema: { type: integer, minimum: 1, maximum: 100 }
          description: Items per page (clamped to 100)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sources: { type: array, items: { type: object } }
                  total: { type: integer }
                  page: { type: integer }
                  limit: { type: integer }
        '401': { description: Unauthorized }
    post:
      summary: Create admin source (ADMIN_PREVIEW=true)
      security:
        - AdminToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, baseUrl]
              properties:
                name: { type: string, minLength: 1, maxLength: 120 }
                baseUrl: { type: string, format: uri }
                notes: { type: string, maxLength: 2000 }
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  source_id: { type: string }
        '401': { description: Unauthorized }
        '413': { description: Payload too large }
  /api/admin/certified/items:
    get:
      summary: List admin items (ADMIN_PREVIEW=true)
      security:
        - AdminToken: []
      parameters:
        - in: query
          name: status
          required: false
          schema: { type: string, enum: [pending, approved, rejected, queued, error] }
          description: Filter by status
        - in: query
          name: source_id
          required: false
          schema: { type: string }
          description: Filter by source ID
        - in: query
          name: q
          required: false
          schema: { type: string, maxLength: 200 }
          description: Search query for title/url
        - in: query
          name: page
          required: false
          schema: { type: integer, minimum: 1 }
          description: Page number for pagination
        - in: query
          name: limit
          required: false
          schema: { type: integer, minimum: 1, maximum: 100 }
          description: Items per page (clamped to 100)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items: { type: array, items: { type: object } }
                  total: { type: integer }
                  page: { type: integer }
                  limit: { type: integer }
        '401': { description: Unauthorized }
  /api/admin/certified/items/ingest:
    post:
      summary: Ingest admin item (ADMIN_PREVIEW=true)
      security:
        - AdminToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, url]
              properties:
                title: { type: string, minLength: 1, maxLength: 200 }
                url: { type: string, format: uri }
                tags: { type: array, items: { type: string, minLength: 1, maxLength: 40 }, maxItems: 20 }
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  item_id: { type: string }
        '401': { description: Unauthorized }
        '413': { description: Payload too large }
  /api/admin/certified/items/{id}:
    get:
      summary: Get admin item by ID (ADMIN_PREVIEW=true)
      security:
        - AdminToken: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
        '401': { description: Unauthorized }
        '404': { description: Not found }
  /api/admin/certified/items/{id}/approve:
    post:
      summary: Approve admin item (ADMIN_PREVIEW=true)
      security:
        - AdminToken: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  id: { type: string }
                  status: { type: string, enum: [approved] }
        '401': { description: Unauthorized }
        '404': { description: Not found }
  /api/admin/certified/items/{id}/reject:
    post:
      summary: Reject admin item (ADMIN_PREVIEW=true)
      security:
        - AdminToken: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  id: { type: string }
                  status: { type: string, enum: [rejected] }
        '401': { description: Unauthorized }
        '404': { description: Not found }
components:
  securitySchemes:
    AdminToken:
      type: apiKey
      in: header
      name: X-Admin-Token
