name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - staging

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Build and push Docker image (linux/amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (amd64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/cerply-api
          tags: |
            type=raw,value=staging,enable=${{ github.ref_name == 'staging' }}
            type=raw,value=staging-latest,enable=${{ github.ref_name == 'staging' }}
            type=sha,format=long
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}

      # Do not push from local; Apple Silicon yields arm64-only.
      - name: Build and push (linux/amd64 only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_TAG=${{ github.ref_name }}
            GIT_SHA=${{ github.sha }}
            IMAGE_CREATED=${{ steps.meta.outputs.created }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

name: CI

on:
  push:
    branches: [main, master, staging]
  pull_request:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: "Deploy Vercel Production"
        required: false
        default: "false"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vercel-preview:
    if: github.event_name == 'pull_request'
    name: Vercel Preview (PRs and non-main pushes)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vercel Preview Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -euo pipefail
          npx vercel pull --yes --environment=preview --token "$VERCEL_TOKEN"
          # Minimal cooldown guard to avoid tight retry loops on rate limits
          npx vercel deploy --prebuilt --token "$VERCEL_TOKEN" || { echo "Preview deploy hit a limit; skipping."; exit 0; }

  vercel-prod:
    if: >
      (github.ref == 'refs/heads/main') &&
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    name: Vercel Production (main/manual)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vercel Production Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -euo pipefail
          npx vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
          # Deploy to production; bail out softly on rate limits
          npx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN" || { echo "Prod deploy skipped due to limit."; exit 0; }
  api:
    name: Build & Test (API)
    runs-on: ubuntu-latest
    env:
      ROLLUP_USE_NODE_JS: 'true'
      ROLLUP_SKIP_NODEJS_NATIVE: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        env:
          NODE_ENV: development
          NPM_CONFIG_PRODUCTION: 'false'
        run: |
          npm ci --workspaces --include-workspace-root --no-audit --no-fund
          git diff --exit-code package-lock.json || (echo "Root lockfile drifted"; exit 1)

      - name: Build API
        run: npm -w api run build

      - name: Run API tests
        env:
          NODE_ENV: test
          RATE_LIMIT_ENABLED: 'false'
          ROLLUP_USE_NODE_JS: 'true'
          ROLLUP_SKIP_NODEJS_NATIVE: '1'
        run: npm -w api test -- --reporter=verbose


      # NEW — start server before smoke
      - name: Start API (background)
        env:

          NODE_ENV: production
          PORT: 8080
          RATE_LIMIT_ENABLED: 'false'
        run: |
          # Launch the API from the workspace so Node can resolve its deps
          npm -w api run start &
          echo $! > /tmp/api_pid.txt

          # Wait up to 60s for /api/health to respond
          for i in {1..60}; do

            if curl -fsS http://localhost:8080/api/health >/dev/null; then
              echo "API is up"
              break
            fi
            sleep 1
          done

          # One last check so the step fails early if server didn't come up
          curl -fsS http://localhost:8080/api/health >/dev/null

      - name: API smoke (health/plan/analytics)
        env:
          SMOKE_ALLOW_503: '1'
        run: |
          chmod +x api/scripts/smoke-local.sh
          bash api/scripts/smoke-local.sh

      - name: DB migrate (if DATABASE_URL)
        if: ${{ env.DATABASE_URL != '' }}
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          npm -w api run db:migrate || true


      - name: API smoke (legacy ingest)
        if: ${{ env.LEGACY_INGEST_SMOKE == 'true' || env.LEGACY_INGEST_SMOKE == '1' }}
        env:
          LEGACY_INGEST_SMOKE: ${{ env.LEGACY_INGEST_SMOKE }}
          API_BASE: http://localhost:8080
        run: |
          chmod +x scripts/smoke-stg.sh
          bash scripts/smoke-stg.sh | sed -n '1,200p'

      - name: Stop API
        if: always()
        run: |
          if [ -f /tmp/api_pid.txt ]; then

            kill "$(cat /tmp/api_pid.txt)" 2>/dev/null || true
          fi
          # Fallback: ensure any lingering API node process is stopped
          pkill -f "node .*api/dist/index.js" 2>/dev/null || true

  pr-typecheck:
    if: ${{ github.event_name == 'pull_request' }}
    name: Typecheck (API & Web)
    runs-on: ubuntu-latest
    env:
      ROLLUP_USE_NODE_JS: 'true'
      ROLLUP_SKIP_NODEJS_NATIVE: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        env:
          NODE_ENV: development
          NPM_CONFIG_PRODUCTION: 'false'
        run: npm ci --workspaces --include-workspace-root --no-audit --no-fund

      - name: Typecheck (api)
        run: npm -w api run typecheck

      - name: Typecheck (web)
        run: npm -w web run typecheck

  docker:
    name: Build & Push Docker image
    needs: api
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      FALLBACK_CREATED: ""
      RENDER_STAGING_DEPLOY_HOOK: ""
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/cerply-api
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/staging' }}
            type=raw,value=staging-latest,enable=${{ github.ref == 'refs/heads/staging' }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Set created timestamp
        id: created
        run: echo "now=$(date -u +%FT%TZ)" >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_TAG=${{ github.ref_name }}
            GIT_SHA=${{ github.sha }}
            IMAGE_CREATED=${{ steps.created.outputs.now }}

      - name: Trigger Render staging deploy (on staging only)
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: echo "staging deploy starting"
      - name: Resolve staging deploy hook
        if: ${{ github.ref == 'refs/heads/staging' }}
        id: staging_hook
        env:
          RENDER_STAGING_DEPLOY_HOOK: ${{ secrets.RENDER_STAGING_DEPLOY_HOOK }}
        run: |
          set -euo pipefail
          HOOK="${RENDER_STAGING_DEPLOY_HOOK:-https://api.render.com/deploy/srv-d34sosgdl3ps73868q0g?key=QtUaDQzEhc0}"
          echo "value=$HOOK" >> "$GITHUB_OUTPUT"
      - name: Trigger Render staging deploy
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: |
          set -euo pipefail
          curl -fsS -X POST "${{ steps.staging_hook.outputs.value }}" >/dev/null

      - name: Wait for staging health
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          BASE: https://cerply-api-staging-latest.onrender.com
          RENDER_RESUME_HEADER: 'x-render-resume: true'
        run: |
          set -euo pipefail
          for i in {1..60}; do
            resp="$(curl -sS -H "$RENDER_RESUME_HEADER" -w "\n%{http_code}" "$BASE/api/health" || true)"
            body="$(echo "$resp" | sed '$d')"
            code="$(echo "$resp" | tail -n1)"
            if [ "$code" = "200" ] && echo "$body" | jq -e '.ok == true' >/dev/null 2>&1; then
              echo "OK: health 200"; echo "$body" | jq .; exit 0
            fi
            if [ "$code" = "503" ] || [ "$code" = "429" ]; then sleep 5; continue; fi
            sleep 5
          done
          echo "Health never reached 200 { ok: true }" >&2; exit 1

      - name: Version + image headers (best-effort)
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          BASE: https://cerply-api-staging-latest.onrender.com
          RENDER_RESUME_HEADER: 'x-render-resume: true'
        run: |
          set -euo pipefail
          curl -sS -D /tmp/vh.txt -H "$RENDER_RESUME_HEADER" "$BASE/api/version" | jq . || true
          echo "--- image headers ---"
          tr -d '\r' < /tmp/vh.txt | grep -Ei '^x-image-(tag|revision|created):' || true
