name: CI

on:
  push:
    branches: [main, master, staging]
  pull_request:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: "Deploy Vercel Production"
        required: false
        default: "false"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  guard-residual-service-refs:
    name: "Guard: residual service refs"
    runs-on: ubuntu-latest
    outputs:
      cerply: ${{ steps.paths.outputs.cerply }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect changed areas
        id: paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cerply:
              - 'cerply/**'
      - name: Fail on forbidden strings
        run: |
          set -euo pipefail
          echo "Scanning for forbidden strings..."

          # Use PCRE to avoid matching cerply-api-staging-latest
          PATTERN='cerply-api-staging(?!-latest)|cerply-api\.onrender\.com|cerply-api-sha-[A-Za-z0-9-]+\.onrender\.com|srv-d31ukuadbo4c739vm180|https://api\.render\.com/deploy/srv-'

          FILES=$(git ls-files | grep -Ev '^(docs/|README|.*\.md$|.*\.bak$|node_modules/|web/node_modules/|api/dist/|api/.*/dist/|api/.*/build/|web/.*/.next/|web/.*/dist/)' | grep -v '^\.github/workflows/ci\.yml$' || true)
          MATCHES=$(echo "$FILES" | xargs -r grep -InP "$PATTERN" || true)
          if [ -n "$MATCHES" ]; then
            echo "Forbidden references found:" >&2
            echo "$MATCHES" >&2
            exit 1
          fi
          echo "OK: no forbidden references found"

  vercel-preview:
    if: github.event_name == 'pull_request'
    name: Vercel Preview (PRs and non-main pushes)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vercel Preview Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -euo pipefail
          npx vercel pull --yes --environment=preview --token "$VERCEL_TOKEN"
          # Minimal cooldown guard to avoid tight retry loops on rate limits
          npx vercel deploy --prebuilt --token "$VERCEL_TOKEN" || { echo "Preview deploy hit a limit; skipping."; exit 0; }

  vercel-prod:
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_prod == 'true'
    name: Vercel Production (main/manual)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vercel Production Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -euo pipefail
          npx vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
          # Deploy to production; bail out softly on rate limits
          npx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN" || { echo "Prod deploy skipped due to limit."; exit 0; }
  api:
    name: Build & Test (API)
    runs-on: ubuntu-latest
    env:
      ROLLUP_USE_NODE_JS: 'true'
      ROLLUP_SKIP_NODEJS_NATIVE: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        env:
          NODE_ENV: development
          NPM_CONFIG_PRODUCTION: 'false'
        run: |
          npm ci --workspaces --include-workspace-root --no-audit --no-fund
          git diff --exit-code package-lock.json || (echo "Root lockfile drifted"; exit 1)

      - name: Build API
        run: npm --workspace ./api run build

      - name: Run API tests
        env:
          NODE_ENV: test
          RATE_LIMIT_ENABLED: 'false'
          ROLLUP_USE_NODE_JS: 'true'
          ROLLUP_SKIP_NODEJS_NATIVE: '1'
        run: npm --workspace ./api test -- --reporter=verbose


      # NEW — start server before smoke
      - name: Start API (background)
        env:

          NODE_ENV: production
          PORT: 8080
          RATE_LIMIT_ENABLED: 'false'
        run: |
          # Launch the API from the workspace so Node can resolve its deps
          npm --workspace ./api run start &
          echo $! > /tmp/api_pid.txt

          # Wait up to 60s for /api/health to respond
          for i in {1..60}; do

            if curl -fsS http://localhost:8080/api/health >/dev/null; then
              echo "API is up"
              break
            fi
            sleep 1
          done

          # One last check so the step fails early if server didn't come up
          curl -fsS http://localhost:8080/api/health >/dev/null

      - name: API smoke (health/plan/analytics)
        env:
          SMOKE_ALLOW_503: '1'
        run: |
          chmod +x api/scripts/smoke-local.sh
          bash api/scripts/smoke-local.sh

      - name: DB migrate (if DATABASE_URL)
        if: ${{ env.DATABASE_URL != '' }}
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          npm -w api run db:migrate || true


      - name: API smoke (legacy ingest)
        if: ${{ env.LEGACY_INGEST_SMOKE == 'true' || env.LEGACY_INGEST_SMOKE == '1' }}
        env:
          LEGACY_INGEST_SMOKE: ${{ env.LEGACY_INGEST_SMOKE }}
          API_BASE: http://localhost:8080
        run: |
          chmod +x scripts/smoke-stg.sh
          bash scripts/smoke-stg.sh | sed -n '1,200p'

      - name: Stop API
        if: always()
        run: |
          if [ -f /tmp/api_pid.txt ]; then

            kill "$(cat /tmp/api_pid.txt)" 2>/dev/null || true
          fi
          # Fallback: ensure any lingering API node process is stopped
          pkill -f "node .*api/dist/index.js" 2>/dev/null || true

  pr-typecheck:
    if: ${{ github.event_name == 'pull_request' }}
    name: Typecheck (API & Web)
    runs-on: ubuntu-latest
    env:
      ROLLUP_USE_NODE_JS: 'true'
      ROLLUP_SKIP_NODEJS_NATIVE: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            web/package-lock.json

      - name: Install deps (monorepo with retry)
        env:
          NODE_ENV: development
          NPM_CONFIG_PRODUCTION: 'false'
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-maxtimeout 120000
          set -e
          for i in 1 2 3; do
            npm ci --workspaces --include-workspace-root --no-audit --no-fund && break
            echo "npm ci failed (attempt $i), retrying…"
            sleep $((i*5))
          done

      - name: Typecheck (api)
        run: npm -w api run typecheck

      - name: Typecheck (web)
        run: npm -w web run typecheck

  cerply-api:
    needs: [guard-residual-service-refs]
    if: ${{ github.event_name == 'pull_request' && needs.guard-residual-service-refs.outputs.cerply == 'true' }}
    name: Cerply Workspace – Build & Test (API)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install deps
        run: npm ci --workspaces --include-workspace-root --no-audit --no-fund
      - name: Build (cerply/api)
        run: npm -w cerply/api run build || true
      - name: Test (cerply/api)
        env:
          NODE_ENV: test
        run: npm -w cerply/api test -- --reporter=verbose || true

  docker:
    name: Build & Push Docker image
    needs: [guard-residual-service-refs, api]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      FALLBACK_CREATED: ""
      RENDER_STAGING_DEPLOY_HOOK: ""
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (amd64 only)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/cerply-api
          tags: |
            type=sha,format=long
            # Tag staging and staging-latest on both staging and main to keep Render staging current
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
            type=raw,value=staging-latest,enable=${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' }}
            # On main, publish prod-candidate and a short sha tag for promotion
            type=raw,value=prod-candidate,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=short,prefix=sha-,enable=${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Compute build args
        id: build_args
        run: echo "created=$(date -u +%FT%TZ)" >> "$GITHUB_OUTPUT"

      # Do not push from local; Apple Silicon yields arm64-only.
      - name: Build & Push (linux/amd64 only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_TAG=${{ github.ref_name }}
            GIT_SHA=${{ github.sha }}
            IMAGE_CREATED=${{ steps.build_args.outputs.created }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check IMAGE_* present in staging-latest
        if: ${{ github.ref_name == 'staging' }}
        run: |
          set -euo pipefail
          IMG="ghcr.io/${{ github.repository_owner }}/cerply-api:staging-latest"
          docker pull "$IMG"
          docker run --rm "$IMG" /bin/sh -lc 'env | grep -E "^IMAGE_|^NODE" || true'
          for k in IMAGE_TAG IMAGE_REVISION IMAGE_CREATED; do
            v=$(docker run --rm "$IMG" /bin/sh -lc "printenv $k || true")
            if [ -z "$v" ]; then
              echo "::error::missing or empty $k in image env" >&2
              exit 1
            fi
          done

      - name: Trigger Render staging deploy
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          RENDER_STAGING_DEPLOY_HOOK: ${{ secrets.RENDER_STAGING_DEPLOY_HOOK }}
        run: |
          set -euo pipefail
          if [ -n "${RENDER_STAGING_DEPLOY_HOOK:-}" ]; then
            curl -fsS -X POST "$RENDER_STAGING_DEPLOY_HOOK" >/dev/null
            echo "Staging deploy triggered via hook"
          else
            echo "No RENDER_STAGING_DEPLOY_HOOK configured; skipping deploy trigger"
          fi

      - name: Wait for staging health
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          BASE: https://cerply-api-staging-latest.onrender.com
          RENDER_RESUME_HEADER: 'x-render-resume: true'
        run: |
          set -euo pipefail
          for i in {1..60}; do
            resp="$(curl -sS -H "$RENDER_RESUME_HEADER" -w "\n%{http_code}" "$BASE/api/health" || true)"
            body="$(echo "$resp" | sed '$d')"
            code="$(echo "$resp" | tail -n1)"
            if [ "$code" = "200" ] && echo "$body" | jq -e '.ok == true' >/dev/null 2>&1; then
              echo "OK: health 200"; echo "$body" | jq .; exit 0
            fi
            if [ "$code" = "503" ] || [ "$code" = "429" ]; then sleep 5; continue; fi
            sleep 5
          done
          echo "Health never reached 200 { ok: true }" >&2; exit 1

      - name: Version + image headers must be non-empty
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          BASE: https://cerply-api-staging-latest.onrender.com
          RENDER_RESUME_HEADER: 'x-render-resume: true'
        run: |
          set -euo pipefail
          curl -sS -D /tmp/vh.txt -H "$RENDER_RESUME_HEADER" "$BASE/api/version" | jq .
          echo "--- image headers ---"
          cat /tmp/vh.txt
          for h in x-image-tag x-image-revision x-image-created; do
            if ! grep -qiE "^$h:\s*[0-9A-Za-z._:-]+" /tmp/vh.txt; then
              echo "::error::header $h missing or empty" >&2
              exit 1
            fi
          done
