name: Nightly Smoke

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check staging
        run: |
          set -euo pipefail
          BASE="https://cerply-api-staging-latest.onrender.com"
          code=$(curl -sS -o /dev/null -w "%{http_code}\n" "$BASE/api/health")
          echo "staging_health=$code"
          test "$code" = "200"
          curl -sS -D /tmp/h.stg "$BASE/api/version" -o /tmp/v.stg.json
          jq -e '.image.tag      | length > 0' /tmp/v.stg.json >/dev/null
          jq -e '.image.revision | length > 0' /tmp/v.stg.json >/dev/null
          jq -e '.image.created  | length > 0' /tmp/v.stg.json >/dev/null
          grep -Ei '^x-image-(tag|revision|created):\s*\S' /tmp/h.stg
          grep -Ei '^x-runtime-channel:\s*\S' /tmp/h.stg

      - name: Check prod
        run: |
          set -euo pipefail
          BASE="https://api.cerply.com"
          code=$(curl -sS -o /dev/null -w "%{http_code}\n" "$BASE/api/health")
          echo "prod_health=$code"
          test "$code" = "200"
          curl -sS -D /tmp/h.prod "$BASE/api/version" -o /tmp/v.prod.json
          # Prod may not advertise image metadata consistently. Treat these as advisory.
          if ! jq -e '.image.tag      | length > 0' /tmp/v.prod.json >/dev/null; then echo "warn: prod .image.tag missing"; fi
          if ! jq -e '.image.revision | length > 0' /tmp/v.prod.json >/dev/null; then echo "warn: prod .image.revision missing"; fi
          if ! jq -e '.image.created  | length > 0' /tmp/v.prod.json >/dev/null; then echo "warn: prod .image.created missing"; fi
          if ! grep -Ei '^x-image-(tag|revision|created):\s*\S' /tmp/h.prod >/dev/null; then echo "warn: prod x-image-* headers missing"; fi
          if ! grep -Ei '^x-runtime-channel:\s*\S' /tmp/h.prod >/dev/null; then echo "warn: prod x-runtime-channel header missing"; fi


