name: PR Preview Teardown

on:
  pull_request:
    types: [unlabeled, closed]
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR number to teardown'
        required: true

permissions:
  contents: read

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  teardown:
    name: Delete preview deployments for PR
    if: >
      (github.event_name == 'workflow_dispatch')
      || (github.event.action == 'unlabeled' && github.event.label.name == 'preview')
      || (github.event.action == 'closed')
    runs-on: ubuntu-latest
    steps:
      - id: meta
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "pr=${{ inputs.pr }}" >> "$GITHUB_OUTPUT"
          else
            echo "pr=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Find deployments by meta.pr
        id: list
        env:
          PR: ${{ steps.meta.outputs.pr }}
        run: |
          curl -fsSL -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v6/deployments?projectId=$VERCEL_PROJECT_ID&meta-pr=$PR&limit=100" \
            > /tmp/deploys.json || echo '{"deployments":[]}' > /tmp/deploys.json
          ids=$(jq -r '.deployments[].uid' /tmp/deploys.json)
          echo "ids=$ids" >> "$GITHUB_OUTPUT"

      - name: Delete deployments
        if: steps.list.outputs.ids != ''
        run: |
          for id in ${{ steps.list.outputs.ids }}; do
            echo "Deleting $id"
            curl -fsS -X DELETE -H "Authorization: Bearer $VERCEL_TOKEN" \
              "https://api.vercel.com/v13/deployments/$id" || true
          done

