name: ssot-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  nudge:
    runs-on: ubuntu-latest
    steps:
      - name: Nudge if BRD/Tech fields are empty
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.pull_request && context.payload.pull_request.body) || "";
            const missing = [];
            if (!/BRD IDs:\s*\S+/i.test(body)) missing.push("BRD IDs");
            if (!/Tech sections:\s*\S+/i.test(body)) missing.push("Tech sections");
            if (missing.length === 0) { core.info("All SSOT fields present."); return; }
            const marker = "[ssot-lint]";
            const comments = await github.paginate(github.rest.issues.listComments, { owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, per_page: 100 });
            const already = comments.some(c => c.user && c.user.type === "Bot" && c.body && c.body.includes(marker));
            if (!already) {
              await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body: marker + " Thanks for the PR! For SSOT governance, please fill in: " + missing.join(", ") + " in the PR description under the template fields (BRD IDs:, Tech sections:). This is a gentle nudge and does not block merging." });
            }
