name: Staging Smoke

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install curl & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Run smoke tests against staging alias
        shell: bash
        run: |
          set -euo pipefail
          # Prefer repo/org variable STG_URL; fall back to a stable Vercel alias.
          STG="${{ vars.STG_URL }}"
          if [[ -z "${STG}" ]]; then
            STG="https://cerply-staging.vercel.app"
          fi
          export STG
          export API_STG="https://api-stg.cerply.com"

          chmod +x scripts/smoke-stg.sh
          ./scripts/smoke-stg.sh
