
name: Web Smoke (API-linked)

on:
  workflow_dispatch:
    inputs:
      api_base:
        description: "API base URL (e.g., https://cerply-api-staging-latest.onrender.com)"
        required: true
        default: "https://cerply-api-staging-latest.onrender.com"
  pull_request:
    paths:
      - "web/**"
      - "api/**"
      - ".github/workflows/web-smoke.yml"

concurrency:
  group: web-smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    continue-on-error: true  # Temporarily non-blocking during header migration
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install web deps (ci)
        run: npm ci

      - name: Run Web Smoke (echo + node)
        env:
          NEXT_PUBLIC_API_BASE: ${{ inputs.api_base || 'https://cerply-api-staging-latest.onrender.com' }}
          SMOKE_TIMEOUT_MS: '15000'
          SMOKE_RETRIES: '6'
        run: |
          set -euo pipefail
          echo '--- scripts/smoke-api.mjs (first 60 lines) ---'
          sed -n '1,60p' scripts/smoke-api.mjs
          node --version
          node scripts/smoke-api.mjs
