name: Workflows Health

on:
  workflow_dispatch:
  push:
    branches:
      - chore/workflows-health
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  lint:
    name: Lint workflows
    runs-on: ubuntu-latest
    steps:
      - name: Fetch workflow files via API
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const ref = context.sha;
            fs.mkdirSync('.github/workflows', { recursive: true });
            const list = await github.rest.repos.getContent({ owner, repo, path: '.github/workflows', ref });
            const entries = Array.isArray(list.data) ? list.data.filter(e => e.type === 'file') : [];
            for (const entry of entries) {
              const file = await github.rest.repos.getContent({ owner, repo, path: entry.path, ref, mediaType: { format: 'raw' } });
              fs.writeFileSync(path.join('.github/workflows', path.basename(entry.path)), Buffer.from(file.data));
            }
            core.notice(`Fetched ${entries.length} workflow files`);

      - name: Set up cache for actionlint
        uses: actions/cache@v4
        with:
          path: ~/.cache/actionlint
          key: ${{ runner.os }}-actionlint-${{ hashFiles('.github/workflows/**') }}
          restore-keys: |
            ${{ runner.os }}-actionlint-

      - name: Download actionlint (with retry)
        shell: bash
        env:
          ACTIONLINT_VERSION: v1.7.1
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.cache/actionlint"
          BIN="$HOME/.cache/actionlint/actionlint"
          if [ ! -x "$BIN" ]; then
            for i in 1 2 3; do
              curl -fsSL "https://github.com/rhysd/actionlint/releases/download/${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION#v}_linux_amd64.tar.gz" -o /tmp/actionlint.tgz && break || sleep 2
            done
            tar -C "$HOME/.cache/actionlint" -xzf /tmp/actionlint.tgz actionlint
            chmod +x "$BIN"
          fi
          echo "$HOME/.cache/actionlint" >> $GITHUB_PATH

      - name: Validate workflow syntax
        run: actionlint -color

  dry-run:
    name: Dry-run common actions
    runs-on: ubuntu-latest
    steps:
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ runner.arch }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Temp project install with retry
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p tmp-proj
          cd tmp-proj
          npm init -y >/dev/null 2>&1 || true
          for i in 1 2 3; do
            npm install --no-audit --no-fund left-pad@1.3.0 && break || {
              echo "npm install failed, retry $i" >&2
              rm -rf node_modules ~/.npm/_cacache || true
              sleep 3
            }
          done
          node -e "console.log(require('left-pad')('ok', 4, '.'))"
